### ISSUE TITLE
3.0.0 release notes

### ISSUE THREAD

**Issue by alexreardon** [alexreardon/bind-event-listener#100]
Draft

----

A **huge** thank you to @Andarist for the TypeScript improvements for `bind-event-listener` that went into this release 👏

### New: Autocomplete for event names 🤩

With TypeScript@5+ you can now get wonderful autocomplete for event names on `EventTarget`'s for `bind` and `bindAll`.

| Before <br/> No auto complete for event names 😢 | After <br/> Auto complete for event names 😁 |
| -------- | -------- |
| <img width="642" alt="Screenshot 2023-04-26 at 4 11 22 pm" src="https://user-images.githubusercontent.com/2182637/234488712-a087c88c-8412-4e5f-807d-a7b38cbf80d6.png"> | <img width="657" alt="Screenshot 2023-04-26 at 4 08 26 pm" src="https://user-images.githubusercontent.com/2182637/234488640-3cf502c0-3452-4073-8a25-bd71d9911ec4.png"> |
| <img width="900" alt="Screenshot 2023-04-27 at 8 41 49 am" src="https://user-images.githubusercontent.com/2182637/234718361-94ea5282-5fab-481d-81e6-29203ea04f25.png"> | <img width="630" alt="Screenshot 2023-04-27 at 8 42 34 am" src="https://user-images.githubusercontent.com/2182637/234718365-e3243404-4b2d-4ec6-b027-01c82402be80.png"> |

- #94 
- #98 

### Change: As many correctly typed event listeners for `bindAll` as you like

`bindAll` previously supported correct typing on up to `12` event listeners. Now, `bindAll` supports correct typing on as many event listeners as you like. To help facilitate this change, we have changed the type signature of `bindAll` from taking strings, to taking an array of strings

```diff
- bindAll<HTMLElement, 'click', 'keydown'>(button, [/*bindings*/]);
+ bindAll<HTMLElement, ['click', 'keydown']>(button, [/*bindings*/]);
```

We generally recommend you don't provide the values for the `bind` or `bindAll` generics, and rather just let them be inferred.

```ts
import { bind, bindAll } from 'bind-event-listener';

const button = document.querySelector('button');
if (!button) {
  return;
}

const unbind = bind(button, { type: 'click', listener(event) {} });

const unbindAll = bindAll(button, [
  { type: 'click', listener(event) {} },
  { type: 'keydown', listener(event) {} },
]);
```

> 💥 This change was listed as a **breaking** change as it changed the public type signature of `bindAll`

- #94 
- #98 

## Other

- Improved clarity of readme #101 
- Bumping dev dependencies #99
- Moved repo to `TypeScript@5` #99
- Type check tests will now run as a part of the build #99

**Comment by alexreardon** [comment]
What do you think @Andarist?

**Comment by Andarist** [comment]
nit: for the `bindAll`'s before/after I would include a two-element tuple and show that the second item can be autocompleted.

**Comment by alexreardon** [comment]
Done

**Comment by alexreardon** [comment]
Now pulished: https://github.com/alexreardon/bind-event-listener/releases/tag/v3.0.0
