### ISSUE TITLE
Typescript: Callbacks which take a MouseEvent/KeyboardEvent raising type errors 

### ISSUE THREAD

**Issue by AndrewOCC** [alexreardon/bind-event-listener#5]
I'm working with this library in a typescript environment, and when passing listeners into bindAll, I've been getting type errors.
From my research it seems like --strictFunctionTypes is causing Typescript to not recognise these listeners as event listeners: (see [this stackoverflow page](https://stackoverflow.com/questions/47166369/argument-of-type-e-customevent-void-is-not-assignable-to-parameter-of-ty)) 

An example of the usage would be the following:
```
    const onKeyDown = (event: KeyboardEvent) => {
      // other logic
    };

    const unbind = bindAll(window, [
      { type: 'keydown', listener: onKeyDown },
    ]);
    return unbind;
```

Listener is highlighted with the error

```
Type '({ target }: MouseEvent) => void' is not assignable to type 'EventListenerOrEventListenerObject'.
  Type '({ target }: MouseEvent) => void' is not assignable to type 'EventListener'.
    Types of parameters '__0' and 'evt' are incompatible.
      Type 'Event' is missing the following properties from type 'MouseEvent': altKey, button, buttons, clientX, and 20 more.ts(2322)
```

**Comment by alexreardon** [comment]
Duplicate: #7
