### ISSUE TITLE
Module gets tree-shaken away

### ISSUE THREAD

**Issue by cdauth** [alexreardon/bind-event-listener#66]
I'm using a library that uses bind-event-listener 1.0.2. My app is bundled using vite, which in production mode is a wrapper for rollup.js.

When building my app (in production mode), the bind-event-listener module becomes an empty object, causing errors to be thrown because its exported functions cannot be found.

The reason seems to be that all exported members of the module get tree-shaked away. The reasons seems to be that this package declares `"sideEffects": false`, but exports its package like this:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var bind_1 = require("./bind");
Object.defineProperty(exports, "bind", { enumerable: true, get: function () { return bind_1.bind; } });
var bind_all_1 = require("./bind-all");
Object.defineProperty(exports, "bindAll", { enumerable: true, get: function () { return bind_all_1.bindAll; } });
```

I'm not an expert on this topic, but to me it doesn't seem to make sense to use `"sideEffects": false` in a package that doesn't even export an ES module, since tree-shaking should not be possible there anyways. The way that the exports are defined in this package does actually look like a side-effect to me.

**Comment by alexreardon** [comment]
Hi @cdauth,

That sounds bad! Could you try out `2.0.0` and see if you are still experiencing issues?

**Comment by alexreardon** [comment]
Please reopen if this is still an issue
